# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Emmanuel Anguiano"          # Your name

  # start of the navigation bar at the top of the website
  navbar:
    pinned: false
    
    # your sub-pages
    left:
      - text: "Curso R"
        href: curso_R/index.qmd
    
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: folder-symlink
        href: https://github.com/eanguianopita?tab=repositories
      - icon: twitter
        href: https://x.com/eanguiano92
      - icon: linkedin
        href: https://www.linkedin.com/in/anguianopita/
      - icon: envelope
        aria-label: email
        href: "mailto:je.ptt@hotmail.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2025 Emmanuel Anguiano CC BY-SA 4.0</span>
 
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: false

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true