project:
  type: website
  output-dir: docs

website:
  title: "Emmanuel Anguiano"
  navbar:
    background: primary
    favicon: Images/Logo.png
    left:
      - text: About
        href: index.qmd
      - text: CV
        href: CV.qmd
      - text: Index
        href: googled3a8645cad571a17.html


format:
  html:
    theme: Yeti
    css: styles.css
    toc: false
    page-layout: full


editor: visual

