project:
  type: website
  output-dir: docs

website:
  title: "Emmanuel Anguiano"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: CV/index.qmd
        text: CV


format:
  html:
    theme: Yeti
    css: styles.css
    toc: false
    page-layout: full


editor: visual

