---
title: "Curriculum Vitae"
format:
  html:
    toc: true
  pdf:
    author: Javier Emmanuel Anguiano Pita
    pdf-engine: weasyprint
css: cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
je.ptt@hotmail.com
:::

## Education

**Doctor of Philosophy -- Economic Studies** <br> *Universidad de Guadalajara (Mexico)* [*Aug 2018 --- May 2022*]{.cvdate}

- Dissertation: *[Essays on North American Economic Integration](https://www.riudg.udg.mx/handle/20.500.12104/20536/browse?type=author&order=ASC&rpp=20&value=Anguiano+Pita%2C+Javier+Emmanuel)*

**Master of Science -- Economics** <br> *Universidad de Guadalajara (Mexico)* [*Aug 2015 --- May 2017*]{.cvdate}
- Thesis: *[Integración de los Mercados Financieros de América del Norte: Un Análisis de los Mercados Monetarios, Cambiarios y Bursátiles durante el periodo 1995-2016](https://riudg.udg.mx/handle/20.500.12104/80101)*

**Bachelor of Science -- Economics** <br> *Universidad de Guadalajara (Mexico)* [*Aug 2010 --- Dic 2014*]{.cvdate}

## Work Experience{style="page-break-before: always"}

### Postdoctoral Fellow

Mexican Council for the Humanities, Sciences and Technology [May 2024 --- Current]{.cvdate}

### Performance Audit Analyst 

Auditoría Superior del Estado de Jalisco (ASEJ) [June 2023 --- Apr 2024]{.cvdate}

### Graduate Research Assistant (Macroeconomic policy analysis)

Plataforma Economía de Jalisco - Universidad de Guadalajara [Aug 2020 --- Dec 2023]{.cvdate}

### Data Scientist and Public Finance Analyst
Instituto para el Desarrollo Técnico de las Haciendas Pública de México [Nov 2017 --- May 2019]{.cvdate}

### Monitoring and Evaluation Manager
National Forestry Commission of Mexico [Jul 2017 --- Nov 2017]{.cvdate}

::: {.no-print}
## PRESENTATIONS AND WORKSHOPS

-   Talk: [Misadventures with Reproducibility in R](https://github.com/cynthiahqy/rladies-2022-11) (30 Nov 2022, R Ladies Melbourne Meetup)
-   Talk: [Designing R Packages](https://github.com/cynthiahqy/design-r-magic_2022-10) (4 Oct 2022, Monash EBS Data Science Research Software Study Group)
-   Talk: [Quarto Websites as Research Compendiums](https://github.com/cynthiahqy/quarto-wiki-template) (16 Aug 2022, Monash EBS Data Science Research Software Study Group)
-   Workshop: [Writing academic papers with Rmarkdown and friends](https://www.cynthiahqy.com/posts/r-markdown-and-friends/) (9 Aug 2022, Monash University)
:::

::: {.print-only}
## References
Available upon request
:::